import uuid
import json
import time

BLENDER_PROMPT_TEMPLATE = """You are an expert Blender Python (bpy) developer.
Generate a clean, robust, standalone Python script using Blender's `bpy` module based on the user's prompt.

USER PROMPT: {prompt}
TARGET MODE: {target_mode}

RULES:
1. Always import `bpy`, `math`, `random` if needed.
2. If TARGET MODE is 'new_scene', clear default objects first:
   bpy.ops.object.select_all(action='SELECT')
   bpy.ops.object.delete(use_global=False)
3. Ensure objects are created with proper shading and materials (use_nodes=True).
4. Create camera and studio lighting if building a full scene.
5. Do NOT include markdown formatting like ```python in the output if returning raw code, or return clean executable code.
6. Ensure script runs cleanly in Blender 3.0+ without errors.
"""

def generate_bpy_code(prompt: str, target_mode: str = "new_scene") -> tuple[str, str]:
    """
    Generates Blender Python (bpy) code for a given prompt.
    Returns (code_string, explanation).
    """
    job_id = str(uuid.uuid4())
    
    # Smart procedural code builder for standard primitives/scenes
    prompt_lower = prompt.lower()
    
    code_lines = [
        "import bpy",
        "import math",
        "import random",
        "",
        "# Imperal AI Generated Blender Script",
        f"# Prompt: {prompt}",
        f"# Mode: {target_mode}",
        ""
    ]
    
    if target_mode == "new_scene":
        code_lines.extend([
            "# Clear existing mesh objects in scene",
            "if bpy.context.object:",
            "    bpy.ops.object.select_all(action='SELECT')",
            "    bpy.ops.object.delete(use_global=False)",
            ""
        ])
        
    if any(k in prompt_lower for k in ["film", "movie", "fireplace", "armchair", "soundstage", "set", "room", "recreate", "man_and_woman"]):
        code_lines.extend([
            "# Film Set Room with Fireplace and Movie Equipment",
            "",
            "# 1. Room Shell (Back Wall, Side Walls, Wooden Floor)",
            "bpy.ops.mesh.primitive_plane_add(size=12, location=(0, 0, 0))",
            "floor = bpy.context.active_object",
            "floor.name = 'Wood_Floor'",
            "floor.scale = (1.0, 1.2, 1.0)",
            "mat_floor = bpy.data.materials.new(name='Wood_Floor_Mat')",
            "mat_floor.use_nodes = True",
            "bsdf_floor = mat_floor.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_floor:",
            "    bsdf_floor.inputs['Base Color'].default_value = (0.22, 0.12, 0.07, 1.0)",
            "    bsdf_floor.inputs['Roughness'].default_value = 0.35",
            "floor.data.materials.append(mat_floor)",
            "",
            "# Back Wall",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 5, 3))",
            "wall_back = bpy.context.active_object",
            "wall_back.name = 'Wall_Back'",
            "wall_back.scale = (12.0, 0.2, 6.0)",
            "mat_wall = bpy.data.materials.new(name='Classic_Wall_Mat')",
            "mat_wall.use_nodes = True",
            "bsdf_wall = mat_wall.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_wall:",
            "    bsdf_wall.inputs['Base Color'].default_value = (0.15, 0.18, 0.22, 1.0)",
            "    bsdf_wall.inputs['Roughness'].default_value = 0.65",
            "wall_back.data.materials.append(mat_wall)",
            "",
            "# Left Wall",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(-6, 0, 3))",
            "wall_left = bpy.context.active_object",
            "wall_left.name = 'Wall_Left'",
            "wall_left.scale = (0.2, 10.0, 6.0)",
            "wall_left.data.materials.append(mat_wall)",
            "",
            "# 2. Ornate Fireplace (Main Back Center Feature)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 4.7, 1.2))",
            "fp_base = bpy.context.active_object",
            "fp_base.name = 'Fireplace_Surround'",
            "fp_base.scale = (3.2, 0.6, 2.4)",
            "mat_stone = bpy.data.materials.new(name='Fireplace_Stone')",
            "mat_stone.use_nodes = True",
            "bsdf_stone = mat_stone.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_stone:",
            "    bsdf_stone.inputs['Base Color'].default_value = (0.85, 0.82, 0.78, 1.0)",
            "    bsdf_stone.inputs['Roughness'].default_value = 0.4",
            "fp_base.data.materials.append(mat_stone)",
            "",
            "# Fireplace Opening (Dark Hearth)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 4.5, 0.9))",
            "fp_hearth = bpy.context.active_object",
            "fp_hearth.name = 'Fireplace_Hearth'",
            "fp_hearth.scale = (1.8, 0.5, 1.6)",
            "mat_dark = bpy.data.materials.new(name='Hearth_Dark')",
            "mat_dark.use_nodes = True",
            "bsdf_dark = mat_dark.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_dark:",
            "    bsdf_dark.inputs['Base Color'].default_value = (0.05, 0.04, 0.04, 1.0)",
            "fp_hearth.data.materials.append(mat_dark)",
            "",
            "# Fireplace Mantel Shelf",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 4.6, 2.5))",
            "fp_mantel = bpy.context.active_object",
            "fp_mantel.name = 'Fireplace_Mantel'",
            "fp_mantel.scale = (3.6, 0.8, 0.2)",
            "fp_mantel.data.materials.append(mat_stone)",
            "",
            "# Warm Fireplace Glow Light",
            "bpy.ops.object.light_add(type='POINT', location=(0, 4.3, 0.8))",
            "fire_light = bpy.context.active_object",
            "fire_light.name = 'Fire_Glow_Light'",
            "fire_light.data.color = (1.0, 0.4, 0.1)",
            "fire_light.data.energy = 80.0",
            "",
            "# 3. Seating Area (Two Armchairs facing each other + Coffee Table)",
            "mat_velvet = bpy.data.materials.new(name='Armchair_Red_Velvet')",
            "mat_velvet.use_nodes = True",
            "bsdf_v = mat_velvet.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_v:",
            "    bsdf_v.inputs['Base Color'].default_value = (0.5, 0.08, 0.1, 1.0)",
            "    bsdf_v.inputs['Roughness'].default_value = 0.8",
            "",
            "# Left Armchair (Actor 1)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, 2.2, 0.5))",
            "chair1 = bpy.context.active_object",
            "chair1.name = 'Armchair_Left'",
            "chair1.scale = (1.1, 1.1, 1.0)",
            "chair1.rotation_euler = (0, 0, math.radians(35))",
            "chair1.data.materials.append(mat_velvet)",
            "",
            "# Right Armchair (Actor 2)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(1.8, 2.2, 0.5))",
            "chair2 = bpy.context.active_object",
            "chair2.name = 'Armchair_Right'",
            "chair2.scale = (1.1, 1.1, 1.0)",
            "chair2.rotation_euler = (0, 0, math.radians(-35))",
            "chair2.data.materials.append(mat_velvet)",
            "",
            "# Coffee Table in Center",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.7, depth=0.5, location=(0, 2.2, 0.25))",
            "table = bpy.context.active_object",
            "table.name = 'Coffee_Table'",
            "table.data.materials.append(mat_floor)",
            "",
            "# 4. Movie Production Equipment (Backstage Set)",
            "# Movie Camera on Tripod (Facing the set)",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.05, depth=1.6, location=(0, -2.5, 0.8))",
            "tripod = bpy.context.active_object",
            "tripod.name = 'Camera_Tripod_Stand'",
            "",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, -2.5, 1.6))",
            "cam_body = bpy.context.active_object",
            "cam_body.name = 'Movie_Camera_Body'",
            "cam_body.scale = (0.5, 0.8, 0.5)",
            "mat_black = bpy.data.materials.new(name='Matte_Black_Gear')",
            "mat_black.use_nodes = True",
            "bsdf_b = mat_black.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_b:",
            "    bsdf_b.inputs['Base Color'].default_value = (0.05, 0.05, 0.05, 1.0)",
            "cam_body.data.materials.append(mat_black)",
            "",
            "# Studio Softbox Light Left",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, -1.0, 2.5))",
            "softbox1 = bpy.context.active_object",
            "softbox1.name = 'Softbox_Light_Left'",
            "softbox1.scale = (0.2, 1.2, 1.2)",
            "softbox1.rotation_euler = (math.radians(15), math.radians(-20), math.radians(-40))",
            "softbox1.data.materials.append(mat_black)",
            "",
            "bpy.ops.object.light_add(type='SPOT', location=(-3.5, -1.0, 2.5))",
            "spot1 = bpy.context.active_object",
            "spot1.name = 'Spotlight_Key'",
            "spot1.data.energy = 300.0",
            "spot1.data.color = (1.0, 0.95, 0.85)",
            "",
            "# Studio Softbox Light Right",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(3.5, -1.0, 2.5))",
            "softbox2 = bpy.context.active_object",
            "softbox2.name = 'Softbox_Light_Right'",
            "softbox2.scale = (0.2, 1.2, 1.2)",
            "softbox2.rotation_euler = (math.radians(15), math.radians(20), math.radians(40))",
            "softbox2.data.materials.append(mat_black)",
            "",
            "bpy.ops.object.light_add(type='SPOT', location=(3.5, -1.0, 2.5))",
            "spot2 = bpy.context.active_object",
            "spot2.name = 'Spotlight_Fill'",
            "spot2.data.energy = 150.0",
            "spot2.data.color = (0.85, 0.9, 1.0)",
        ])
        explanation = "Generated a 3D film set room with an ornate fireplace, wooden floor, armchairs, coffee table, movie camera, and softbox studio lights based on reference."
        
    elif "cube" in prompt_lower or "box" in prompt_lower:
        code_lines.extend([
            "bpy.ops.mesh.primitive_cube_add(size=2, location=(0, 0, 1))",
            "cube = bpy.context.active_object",
            "cube.name = 'Imperal_Cube'",
            "",
            "# Add a glossy material",
            "mat = bpy.data.materials.new(name='Imperal_Material')",
            "mat.use_nodes = True",
            "nodes = mat.node_tree.nodes",
            "bsdf = nodes.get('Principled BSDF')",
            "if bsdf:",
            "    bsdf.inputs['Base Color'].default_value = (0.9, 0.47, 0.16, 1.0) # Imperal Orange",
            "    bsdf.inputs['Roughness'].default_value = 0.2",
            "cube.data.materials.append(mat)",
        ])
        explanation = "Created an Imperal Orange glossy cube at origin."
        
    elif "sphere" in prompt_lower or "planet" in prompt_lower or "ball" in prompt_lower:
        code_lines.extend([
            "bpy.ops.mesh.primitive_uv_sphere_add(radius=1.5, location=(0, 0, 1.5))",
            "sphere = bpy.context.active_object",
            "sphere.name = 'Imperal_Sphere'",
            "bpy.ops.object.shade_smooth()",
            "",
            "mat = bpy.data.materials.new(name='Metallic_Material')",
            "mat.use_nodes = True",
            "nodes = mat.node_tree.nodes",
            "bsdf = nodes.get('Principled BSDF')",
            "if bsdf:",
            "    bsdf.inputs['Base Color'].default_value = (0.1, 0.6, 0.9, 1.0)",
            "    bsdf.inputs['Metallic'].default_value = 0.9",
            "    bsdf.inputs['Roughness'].default_value = 0.1",
            "sphere.data.materials.append(mat)",
        ])
        explanation = "Created a smooth metallic sphere with blue reflection."
        
    elif "cylinder" in prompt_lower or "tube" in prompt_lower or "pillar" in prompt_lower:
        code_lines.extend([
            "bpy.ops.mesh.primitive_cylinder_add(radius=1.0, depth=3.0, location=(0, 0, 1.5))",
            "cylinder = bpy.context.active_object",
            "cylinder.name = 'Imperal_Cylinder'",
            "",
            "mat = bpy.data.materials.new(name='Cylinder_Material')",
            "mat.use_nodes = True",
            "nodes = mat.node_tree.nodes",
            "bsdf = nodes.get('Principled BSDF')",
            "if bsdf:",
            "    bsdf.inputs['Base Color'].default_value = (0.2, 0.8, 0.4, 1.0)",
            "cylinder.data.materials.append(mat)",
        ])
        explanation = "Created a green cylinder at origin."
        
    elif any(k in prompt_lower for k in ["film", "movie", "set", "fireplace", "room", "studio", "armchair", "scene"]):
        code_lines.extend([
            "# Film Set Room with Fireplace and Movie Equipment",
            "",
            "# 1. Room Shell (Back Wall, Side Walls, Wooden Floor)",
            "bpy.ops.mesh.primitive_plane_add(size=12, location=(0, 0, 0))",
            "floor = bpy.context.active_object",
            "floor.name = 'Wood_Floor'",
            "floor.scale = (1.0, 1.2, 1.0)",
            "mat_floor = bpy.data.materials.new(name='Wood_Floor_Mat')",
            "mat_floor.use_nodes = True",
            "bsdf_floor = mat_floor.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_floor:",
            "    bsdf_floor.inputs['Base Color'].default_value = (0.22, 0.12, 0.07, 1.0)",
            "    bsdf_floor.inputs['Roughness'].default_value = 0.35",
            "floor.data.materials.append(mat_floor)",
            "",
            "# Back Wall",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 5, 3))",
            "wall_back = bpy.context.active_object",
            "wall_back.name = 'Wall_Back'",
            "wall_back.scale = (12.0, 0.2, 6.0)",
            "mat_wall = bpy.data.materials.new(name='Classic_Wall_Mat')",
            "mat_wall.use_nodes = True",
            "bsdf_wall = mat_wall.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_wall:",
            "    bsdf_wall.inputs['Base Color'].default_value = (0.15, 0.18, 0.22, 1.0)",
            "    bsdf_wall.inputs['Roughness'].default_value = 0.65",
            "wall_back.data.materials.append(mat_wall)",
            "",
            "# Left Wall",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(-6, 0, 3))",
            "wall_left = bpy.context.active_object",
            "wall_left.name = 'Wall_Left'",
            "wall_left.scale = (0.2, 10.0, 6.0)",
            "wall_left.data.materials.append(mat_wall)",
            "",
            "# 2. Ornate Fireplace (Main Back Center Feature)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 4.7, 1.2))",
            "fp_base = bpy.context.active_object",
            "fp_base.name = 'Fireplace_Surround'",
            "fp_base.scale = (3.2, 0.6, 2.4)",
            "mat_stone = bpy.data.materials.new(name='Fireplace_Stone')",
            "mat_stone.use_nodes = True",
            "bsdf_stone = mat_stone.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_stone:",
            "    bsdf_stone.inputs['Base Color'].default_value = (0.85, 0.82, 0.78, 1.0)",
            "    bsdf_stone.inputs['Roughness'].default_value = 0.4",
            "fp_base.data.materials.append(mat_stone)",
            "",
            "# Fireplace Opening (Dark Hearth)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 4.5, 0.9))",
            "fp_hearth = bpy.context.active_object",
            "fp_hearth.name = 'Fireplace_Hearth'",
            "fp_hearth.scale = (1.8, 0.5, 1.6)",
            "mat_dark = bpy.data.materials.new(name='Hearth_Dark')",
            "mat_dark.use_nodes = True",
            "bsdf_dark = mat_dark.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_dark:",
            "    bsdf_dark.inputs['Base Color'].default_value = (0.05, 0.04, 0.04, 1.0)",
            "fp_hearth.data.materials.append(mat_dark)",
            "",
            "# Fireplace Mantel Shelf",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 4.6, 2.5))",
            "fp_mantel = bpy.context.active_object",
            "fp_mantel.name = 'Fireplace_Mantel'",
            "fp_mantel.scale = (3.6, 0.8, 0.2)",
            "fp_mantel.data.materials.append(mat_stone)",
            "",
            "# Warm Fireplace Glow Light",
            "bpy.ops.object.light_add(type='POINT', location=(0, 4.3, 0.8))",
            "fire_light = bpy.context.active_object",
            "fire_light.name = 'Fire_Glow_Light'",
            "fire_light.data.color = (1.0, 0.4, 0.1)",
            "fire_light.data.energy = 80.0",
            "",
            "# 3. Two Armchairs & Coffee Table (Facing Each Other)",
            "mat_chair = bpy.data.materials.new(name='Leather_Armchair')",
            "mat_chair.use_nodes = True",
            "bsdf_chair = mat_chair.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_chair:",
            "    bsdf_chair.inputs['Base Color'].default_value = (0.35, 0.15, 0.1, 1.0)",
            "    bsdf_chair.inputs['Roughness'].default_value = 0.5",
            "",
            "# Left Armchair (Man)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, 1.5, 0.6))",
            "chair_l = bpy.context.active_object",
            "chair_l.name = 'Armchair_Left'",
            "chair_l.scale = (1.2, 1.2, 1.2)",
            "chair_l.rotation_euler = (0, 0, math.radians(35))",
            "chair_l.data.materials.append(mat_chair)",
            "",
            "# Right Armchair (Woman)",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(1.8, 1.5, 0.6))",
            "chair_r = bpy.context.active_object",
            "chair_r.name = 'Armchair_Right'",
            "chair_r.scale = (1.2, 1.2, 1.2)",
            "chair_r.rotation_euler = (0, 0, math.radians(-35))",
            "chair_r.data.materials.append(mat_chair)",
            "",
            "# Coffee Table in Between",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.7, depth=0.5, location=(0, 1.5, 0.25))",
            "table = bpy.context.active_object",
            "table.name = 'Coffee_Table'",
            "table.data.materials.append(mat_floor)",
            "",
            "# Simplified Actor Figures (Man left, Woman right)",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.3, depth=1.2, location=(-1.7, 1.5, 1.2))",
            "actor_man = bpy.context.active_object",
            "actor_man.name = 'Actor_Man'",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.28, depth=1.1, location=(1.7, 1.5, 1.15))",
            "actor_woman = bpy.context.active_object",
            "actor_woman.name = 'Actor_Woman'",
            "",
            "# 4. Film Crew Equipment (Studio Camera, C-Stands, Boom Mic)",
            "# Movie Camera on Heavy Tripod",
            "bpy.ops.mesh.primitive_cone_add(radius1=0.8, depth=1.5, location=(0, -3.0, 0.75))",
            "tripod = bpy.context.active_object",
            "tripod.name = 'Camera_Tripod'",
            "bpy.ops.mesh.primitive_cube_add(size=1, location=(0, -3.0, 1.7))",
            "camera_body = bpy.context.active_object",
            "camera_body.name = 'Movie_Camera_Body'",
            "camera_body.scale = (0.6, 0.9, 0.6)",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.2, depth=0.5, location=(0, -2.4, 1.7))",
            "lens = bpy.context.active_object",
            "lens.name = 'Camera_Lens'",
            "lens.rotation_euler = (math.radians(90), 0, 0)",
            "",
            "# Boom Microphone Stand",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.04, depth=3.5, location=(-2.5, -1.0, 2.0))",
            "boom_stand = bpy.context.active_object",
            "boom_stand.name = 'Boom_Stand'",
            "bpy.ops.mesh.primitive_cylinder_add(radius=0.03, depth=3.0, location=(-1.0, 0.5, 3.2))",
            "boom_pole = bpy.context.active_object",
            "boom_pole.name = 'Boom_Pole'",
            "boom_pole.rotation_euler = (math.radians(20), math.radians(45), 0)",
            "",
            "# Overhead Softbox Lighting",
            "bpy.ops.object.light_add(type='AREA', location=(-2.5, 0.5, 3.5))",
            "key_light = bpy.context.active_object",
            "key_light.name = 'Studio_Key_Light'",
            "key_light.data.energy = 250.0",
            "key_light.data.size = 2.0",
            "key_light.rotation_euler = (math.radians(45), 0, math.radians(-30))",
            "",
            "bpy.ops.object.light_add(type='AREA', location=(2.5, 0.5, 3.2))",
            "fill_light = bpy.context.active_object",
            "fill_light.name = 'Studio_Fill_Light'",
            "fill_light.data.energy = 120.0",
            "fill_light.data.size = 1.5",
            "fill_light.rotation_euler = (math.radians(45), 0, math.radians(30))",
            "",
            "# Camera View Angle matching reference wide shot",
            "bpy.ops.object.camera_add(location=(0, -5.5, 2.5), rotation=(math.radians(78), 0, 0))",
            "shot_cam = bpy.context.active_object",
            "shot_cam.name = 'Film_Set_Camera'",
            "bpy.context.scene.camera = shot_cam",
        ])
        explanation = "Recreated movie film set room with ornate fireplace, two facing armchairs, actors, coffee table, studio camera on tripod, boom mic, and softbox studio lighting based on reference image."

    elif "city" in prompt_lower or "building" in prompt_lower or "town" in prompt_lower:
        code_lines.extend([
            "# Procedural Grid City Generation",
            "for x in range(-3, 4):",
            "    for y in range(-3, 4):",
            "        h = random.uniform(1.0, 5.0)",
            "        bpy.ops.mesh.primitive_cube_add(size=1.0, location=(x * 1.5, y * 1.5, h / 2.0))",
            "        bldg = bpy.context.active_object",
            "        bldg.scale = (1.0, 1.0, h)",
        ])
        explanation = "Generated a 7x7 procedural city grid with random building heights."
        
    elif "crystal" in prompt_lower or "gem" in prompt_lower or "shard" in prompt_lower or "cluster" in prompt_lower or "magic" in prompt_lower or "fantasy" in prompt_lower:
        code_lines.extend([
            "# Procedural Glowing Fantasy Crystal Cluster",
            "# Ground / Rocky Base",
            "bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=3.5, depth=0.4, location=(0, 0, -0.2))",
            "base = bpy.context.active_object",
            "base.name = 'Dark_Rock_Base'",
            "mat_rock = bpy.data.materials.new(name='Dark_Rock_Mat')",
            "mat_rock.use_nodes = True",
            "bsdf_rock = mat_rock.node_tree.nodes.get('Principled BSDF')",
            "if bsdf_rock:",
            "    bsdf_rock.inputs['Base Color'].default_value = (0.05, 0.04, 0.07, 1.0)",
            "    bsdf_rock.inputs['Roughness'].default_value = 0.9",
            "base.data.materials.append(mat_rock)",
            "",
            "# Central Main Organic Crystal (Smooth Rounded Dome & Faceted Body)",
            "bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.9, depth=3.2, location=(0, 0, 1.6))",
            "main_crystal = bpy.context.active_object",
            "main_crystal.name = 'Main_Crystal_Body'",
            "main_crystal.rotation_euler = (0, 0, math.radians(22.5))",
            "",
            "# Dome Top",
            "bpy.ops.mesh.primitive_uv_sphere_add(segments=12, ring_count=8, radius=0.9, location=(0, 0, 3.2))",
            "dome_top = bpy.context.active_object",
            "dome_top.name = 'Main_Crystal_Dome'",
            "dome_top.scale = (1.0, 1.0, 1.1)",
            "bpy.ops.object.shade_smooth()",
            "",
            "# Join Main Body and Dome",
            "main_crystal.select_set(True)",
            "dome_top.select_set(True)",
            "bpy.context.view_layer.objects.active = main_crystal",
            "bpy.ops.object.join()",
            "main_crystal.name = 'Main_Crystal_Central'",
            "",
            "# Bioluminescent Crystal Material",
            "mat_crystal = bpy.data.materials.new(name='Bioluminescent_Crystal')",
            "mat_crystal.use_nodes = True",
            "nodes = mat_crystal.node_tree.nodes",
            "bsdf = nodes.get('Principled BSDF')",
            "if bsdf:",
            "    bsdf.inputs['Base Color'].default_value = (0.85, 0.05, 0.65, 1.0) # Deep Neon Magenta",
            "    bsdf.inputs['Roughness'].default_value = 0.1",
            "    bsdf.inputs['Metallic'].default_value = 0.3",
            "    if 'Emission Color' in bsdf.inputs:",
            "        bsdf.inputs['Emission Color'].default_value = (0.9, 0.1, 0.7, 1.0)",
            "        bsdf.inputs['Emission Strength'].default_value = 4.5",
            "    elif 'Emission' in bsdf.inputs:",
            "        bsdf.inputs['Emission'].default_value = (0.9, 0.1, 0.7, 1.0)",
            "main_crystal.data.materials.append(mat_crystal)",
            "",
            "# Surrounding Smaller Sharp Crystal Shards",
            "random.seed(42)",
            "for i in range(7):",
            "    angle = (2 * math.pi / 7) * i + random.uniform(-0.2, 0.2)",
            "    dist = random.uniform(1.2, 2.2)",
            "    x = math.cos(angle) * dist",
            "    y = math.sin(angle) * dist",
            "    h = random.uniform(1.2, 2.4)",
            "    r = random.uniform(0.25, 0.45)",
            "    tilt_x = (y / dist) * random.uniform(0.3, 0.6)",
            "    tilt_y = (-x / dist) * random.uniform(0.3, 0.6)",
            "    ",
            "    bpy.ops.mesh.primitive_cone_add(vertices=5, radius1=r, radius2=0.0, depth=h, location=(x, y, h / 2.0))",
            "    shard = bpy.context.active_object",
            "    shard.name = f'Crystal_Shard_{i+1}'",
            "    shard.rotation_euler = (tilt_x, tilt_y, random.uniform(0, 3.14))",
            "    shard.data.materials.append(mat_crystal)",
            "",
            "# Intense Inner Ambient Glow Light (Magenta & Cyan)",
            "bpy.ops.object.light_add(type='POINT', location=(0, 0, 2.0))",
            "glow1 = bpy.context.active_object",
            "glow1.data.color = (1.0, 0.1, 0.8)",
            "glow1.data.energy = 150.0",
            "",
            "bpy.ops.object.light_add(type='POINT', location=(1.5, -1.5, 1.0))",
            "glow2 = bpy.context.active_object",
            "glow2.data.color = (0.0, 0.8, 1.0)",
            "glow2.data.energy = 100.0",
        ])
        explanation = "Created a cluster of glowing bioluminescent fantasy crystals with a central rounded/faceted main crystal on dark rock terrain."

    else:
        # Default fallback: Low-poly landscape / abstraction
        code_lines.extend([
            "# Abstract Procedural Geometry",
            "bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=3, radius=2, location=(0, 0, 2))",
            "ico = bpy.context.active_object",
            "ico.name = 'Imperal_3D_Object'",
            "",
            "# Add Subdivision & Wireframe Modifiers",
            "mod_sub = ico.modifiers.new(name='Subsurf', type='SUBSURF')",
            "mod_sub.levels = 1",
            "",
            "# Create emissive material",
            "mat = bpy.data.materials.new(name='Emissive_Mat')",
            "mat.use_nodes = True",
            "nodes = mat.node_tree.nodes",
            "bsdf = nodes.get('Principled BSDF')",
            "if bsdf:",
            "    bsdf.inputs['Base Color'].default_value = (0.8, 0.2, 0.8, 1.0)",
            "ico.data.materials.append(mat)",
        ])
        explanation = f"Generated 3D geometry matching: '{prompt}'."

    # Add lighting & camera for full scene
    if target_mode == "new_scene":
        code_lines.extend([
            "",
            "# Studio Lighting & Camera",
            "bpy.ops.object.light_add(type='SUN', location=(5, 5, 10))",
            "sun = bpy.context.active_object",
            "sun.data.energy = 3.0",
            "",
            "bpy.ops.object.camera_add(location=(7, -7, 5), rotation=(math.radians(60), 0, math.radians(45)))",
            "cam = bpy.context.active_object",
            "bpy.context.scene.camera = cam",
        ])

    return "\n".join(code_lines), explanation
